<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoanLens.Domain\LoanLens.Domain.csproj" />
    <ProjectReference Include="..\LoanLens.Infrastructure\LoanLens.Infrastructure.csproj" />
  </ItemGroup>

</Project>
